# Site settings
title: Engine Flight Manual
email: info@enginecomerce.com
description: Engine Commerce reference for software development policies and product and project management
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: enginecommerce
github_username:  enginecommerce
timezone: America/Chicago

# Build settings
encoding: utf-8
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compressed

# Content settings
search_enabled: true
theme: just-the-docs
aux_links:
  "Ecommerce Platform":
    - "https://enginecommerce.com"
  "Ecommerce Email":
    - "https://enginemail.io"
permalink: pretty

# Plugins, etc.
google_tag_manager_id: GTM-NQZFWJC

# Security
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
